[package]
name = "rig-helixdb"
version = "0.1.8"
edition.workspace = true
license = "MIT"
readme = "README.md"
description = "Rig vector store index integration for HelixDB."
repository = "https://github.com/0xPlaygrounds/rig"

[lints]
workspace = true

[dependencies]
helix-rs = "0.1.9"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
rig-core = { path = "../../rig/rig-core", version = "0.28.0", default-features = false }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[[example]]
name = "vector_search_helixdb"
required-features = ["rig-core/derive"]
