[[package]]
name = "rig-core"
version_group = "rig-version"

[[package]]
name = "rig-derive"
version_group = "rig-version"

[[package]]
name = "rig-bedrock"
version_group = "rig-version"

[[package]]
name = "rig-fastembed"
version_group = "rig-version"

[[package]]
name = "rig-helixdb"
version_group = "rig-version"

[[package]]
name = "rig-lancedb"
version_group = "rig-version"

[[package]]
name = "rig-milvus"
version_group = "rig-version"

[[package]]
name = "rig-mongodb"
version_group = "rig-version"

[[package]]
name = "rig-neo4j"
version_group = "rig-version"

[[package]]
name = "rig-postgres"
version_group = "rig-version"

[[package]]
name = "rig-qdrant"
version_group = "rig-version"

[[package]]
name = "rig-s3vectors"
version_group = "rig-version"

[[package]]
name = "rig-scylladb"
version_group = "rig-version"

[[package]]
name = "rig-sqlite"
version_group = "rig-version"

[[package]]
name = "rig-surrealdb"
version_group = "rig-version"

[[package]]
name = "rig-vertexai"
version_group = "rig-version"
