[package]
name = "rig-lancedb"
version = "0.1.1"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "Rig vector store index integration for LanceDB."
repository = "https://github.com/0xPlaygrounds/rig"

[dependencies]
lancedb = "0.10.0"
rig-core = { path = "../rig-core", version = "0.3.1" }
arrow-array = "52.2.0"
serde_json = "1.0.128"
serde = "1.0.210"
futures = "0.3.30"

[dev-dependencies]
tokio = "1.40.0"
anyhow = "1.0.89"
