[package]
name = "rig-gemini-grpc"
version = "0.1.0"
edition.workspace = true
license = "MIT"
readme = "README.md"
description = "Google Gemini gRPC API integration for Rig"
repository = "https://github.com/0xPlaygrounds/rig"

[lints]
workspace = true

[dependencies]
rig-core = { path = "../../rig/rig-core", version = "0.29.0", default-features = false }
async-stream = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
prost = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tonic = { workspace = true, features = ["tls", "transport", "tls-webpki-roots", "zstd", "gzip"] }
tracing = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
protoc-bin-vendored = "3.2.0"

[dev-dependencies]
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
