[package]
name = "rig-vertexai"
version = "0.2.3"
edition.workspace = true
license = "MIT"
readme = "README.md"
description = "VertexAI model provider for Rig integration."

[lints]
workspace = true

[dependencies]
google-cloud-aiplatform-v1 = { workspace = true }
google-cloud-auth = { workspace = true }
rig-core = { path = "../../rig/rig-core", version = "0.28.0", default-features = false }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
schemars = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true }
