[package]
name = "rig-derive"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Internal crate that implements Rig derive macros."
repository = "https://github.com/0xPlaygrounds/rig"

[dependencies]
convert_case = { version = "0.6.0" }
indoc = "2.0.5"
proc-macro2 = { version = "1.0.87", features = ["proc-macro"] }
quote = "1.0.37"
serde_json = "1.0.108"
syn = { version = "2.0.79", features = ["full"]}

[lib]
proc-macro = true

[dev-dependencies]
rig-core = { path = "../../rig-core" }
serde = "1.0"
serde_json = "1.0.108"
tokio = { version = "1.44.0", features = ["full"] }
tracing-subscriber = "0.3.0"

[[example]]
name = "simple"
path = "examples/rig_tool/simple.rs"

[[example]]
name = "with_description"
path = "examples/rig_tool/with_description.rs"

[[example]]
name = "full"
path = "examples/rig_tool/full.rs"

[[example]]
name = "async_tool"
path = "examples/rig_tool/async_tool.rs"
